apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: strimzi-kafka  # Same namespace as the cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
      - name: kafka-connect
        image: debezium/connect:2.5
        ports:
        - containerPort: 8083
          name: http
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kraft-cluster-kafka-bootstrap.strimzi-kafka.svc.cluster.local:9092"  # Modified address
        - name: GROUP_ID
          value: "connect-cluster"  # Changed to meaningful group ID
        - name: CONFIG_STORAGE_TOPIC
          value: "connect-configs"
        - name: OFFSET_STORAGE_TOPIC
          value: "connect-offsets"
        - name: STATUS_STORAGE_TOPIC
          value: "connect-statuses"
        - name: KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: VALUE_CONVERTER 
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: KEY_CONVERTER_SCHEMAS_ENABLE
          value: "true"
        - name: VALUE_CONVERTER_SCHEMAS_ENABLE
          value: "true"
        # Additional settings for Strimzi Kafka cluster
        - name: CONFIG_STORAGE_REPLICATION_FACTOR
          value: "3"  # Matches cluster replication factor
        - name: OFFSET_STORAGE_REPLICATION_FACTOR
          value: "3"  # Matches cluster replication factor
        - name: STATUS_STORAGE_REPLICATION_FACTOR
          value: "3"  # Matches cluster replication factor
        - name: CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY
          value: "All"  # Connector config override policy
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: strimzi-kafka  # Same namespace as the cluster
spec:
  selector:
    app: kafka-connect
  ports:
  - port: 8083
    targetPort: 8083
    name: http