apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: kraft-cluster
spec:
  replicas: 3
  roles:
  - controller
  - broker
  storage:
    type: persistent-claim
    class: standard-rwo       # Using GKE default storage class
    size: 10Gi
    deleteClaim: false
    # kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kraft-cluster
  namespace: strimzi-kafka
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.8.0
    metadataVersion: "3.8"
    replicas: 3
    resources:
      requests:
        memory: 1Gi
        cpu: "1"
      limits:
        memory: 4Gi
        cpu: "3"
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool    # Using GKE nodepool label
                  operator: Exists
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: external
      port: 9094
      type: loadbalancer
      tls: false
      configuration:
        brokers: []  # An empty array means not exposing individual brokers
    logging:
      type: inline
      loggers:
        log4j.logger.io.strimzi: "DEBUG"
        log4j.logger.kafka: "DEBUG"
        log4j.logger.org.apache.kafka: "DEBUG"
    config:
      # Enable KRaft mode
      inter.broker.protocol.version: "3.8"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    storage:
      type: persistent-claim
      size: 20Gi
      class: standard-rwo      # Using GKE default storage class
      deleteClaim: false
  entityOperator:
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool    # Using GKE nodepool label
                  operator: Exists
    topicOperator: {}
    userOperator: {}