apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect
  namespace: strimzi-kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.5.1
  replicas: 1
  image: quay.io/strimzi/kafka:0.37.0-kafka-3.5.1
  bootstrapServers: kraft-cluster-kafka-bootstrap.strimzi-kafka.svc.cluster.local:9092
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-offsets
    config.storage.topic: connect-configs
    status.storage.topic: connect-statuses
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: "true"
    value.converter.schemas.enable: "true"
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
    connector.client.config.override.policy: All
  template:
    connectContainer:
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: iceberg-s3-creds
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: iceberg-s3-creds
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_REGION
        value: "us-east-1"
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 2000m
  build:
    output:
      type: docker
      image: silverstar456/lakehouse-kafka-connect:latest
    plugins:
    - name: debezium-postgres-connector
      artifacts:
      - type: tgz
        url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgresql/2.4.0.Final/debezium-connector-postgresql-2.4.0.Final-plugin.tar.gz
    - name: iceberg-connector
      artifacts:
      - type: zip
        url: https://github.com/tabular-io/iceberg-kafka-connect/releases/download/v0.6.19/iceberg-kafka-connect-0.6.19.zip
---
apiVersion: v1
kind: Secret
metadata:
  name: iceberg-s3-creds
  namespace: strimzi-kafka
type: Opaque
data:
  AWS_ACCESS_KEY_ID: TzhKVk9ZNFFRNkkyUVBEMFNMQUc=
  AWS_SECRET_ACCESS_KEY: QU9EQ0NiWFFIWmZRNHZYWXJvTzlzYVY3azFHYnpXMkhBNmphREo4Sg==