apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: iceberg-sink-connector
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  class: io.tabular.iceberg.connect.IcebergSinkConnector
  tasksMax: 1
  config:
    topics: backend.public.items
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    
    # Iceberg 테이블 구성
    iceberg.tables: itemsdemo
    
    # Iceberg 카탈로그 구성
    iceberg.catalog: rest
    iceberg.catalog.type: rest
    iceberg.catalog.uri: http://iceberg-rest-catalog.iceberg.svc.cluster.local:8181
    iceberg.catalog.warehouse: s3://iceberg-warehouse/
    
    # S3 인증 정보
    iceberg.catalog.credential: static
    iceberg.catalog.credential.static.access-key: ${env:AWS_ACCESS_KEY_ID}
    iceberg.catalog.credential.static.secret-key: ${env:AWS_SECRET_ACCESS_KEY}
    
    # S3 엔드포인트 (Rook-Ceph)
    iceberg.catalog.s3.endpoint-url: http://rook-ceph-rgw-my-store.rook-ceph.svc.cluster.local:80
    iceberg.catalog.s3.path-style-access: true
    iceberg.catalog.client.region: us-east-1
    
    # 커밋 구성
    iceberg.control.commit-interval-ms: 30000
    iceberg.control.commit-timeout-ms: 300000
    iceberg.commit-all: true
    
    # 쓰기 모드 구성
    iceberg.control.properties.delete-mode: copy-on-write
    iceberg.control.properties.upsert-mode: copy-on-write