apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-my-store-external
  namespace: rook-ceph
  labels:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: my-store
spec:
  ports:
  - name: rgw
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: my-store
  type: NodePort
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rook-ceph-mgr-dashboard-loadbalancer
#   namespace: rook-ceph # namespace:cluster
#   labels:
#     app: rook-ceph-mgr
#     rook_cluster: rook-ceph # namespace:cluster
# spec:
#   ports:
#     - name: dashboard
#       port: 8443
#       protocol: TCP
#       targetPort: 8443
#   selector:
#     app: rook-ceph-mgr
#     mgr_role: active
#     rook_cluster: rook-ceph # namespace:cluster
#   sessionAffinity: None
#   type: LoadBalancer