apiVersion: v1
kind: Service
metadata:
  name: fastapi-items-app
  labels:
    app: fastapi-items-app
spec:
  selector:
    app: fastapi-items-app
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: NodePort